# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoG6tqYauAw5Fnc1axKWixIuKDTjUdfz
"""

# -*- coding: utf-8 -*-
"""
Guardian AI - Traffic-Aware Routing with Critical Congestion Detours & Multi-ML Engine
"""

# --- 1. AUTOMATIC DEPENDENCY INSTALLER ---
import sys
import subprocess

def install_packages():
    required_packages = [
        'osmnx', 'folium', 'networkx', 'scipy', 'numpy',
        'matplotlib', 'ipywidgets', 'geopy', 'scikit-learn', 'pandas',
        'xgboost', 'lightgbm', 'requests'
    ]
    for package in required_packages:
        try:
            __import__(package)
        except ImportError:
            print(f"Installing {package}...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", package])

install_packages()

# --- 2. IMPORTS ---
import osmnx as ox
import folium
from folium.plugins import HeatMap
import networkx as nx
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ipywidgets as widgets
import base64
import requests
import warnings
from IPython.display import display, clear_output, HTML
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# ML Models
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, PoissonRegressor
from sklearn.cluster import KMeans
import xgboost as xgb
import lightgbm as lgb

warnings.filterwarnings('ignore')

# --- 3. API CONFIGURATION & FETCHERS ---
TOMTOM_API_KEY = "YOUR_TOMTOM_API_KEY"

geolocator = Nominatim(user_agent="guardian_ai_detour_v14")
reverse = RateLimiter(geolocator.reverse, min_delay_seconds=0.05)
city_cache = {}
address_cache = {}

TILE_PROVIDER = "OpenStreetMap"

def fetch_live_weather(lat=41.81, lng=-87.80):
    """UA: Погода через Open-Meteo API. / EN: Weather via Open-Meteo API."""
    try:
        url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lng}&current=temperature_2m,precipitation&timezone=auto"
        res = requests.get(url, timeout=4).json()
        current = res.get('current', {})
        return {
            'temp': float(current.get('temperature_2m', 20.0)),
            'rain': float(current.get('precipitation', 0.0))
        }
    except Exception:
        return {'temp': 20.0, 'rain': 0.0}

def fetch_live_traffic_factor(lat=41.81, lng=-87.80, api_key=TOMTOM_API_KEY):
    """UA: Затори через TomTom API. / EN: Traffic via TomTom API."""
    if api_key == "YOUR_TOMTOM_API_KEY":
        return 2.2  # Default to critical traffic for detour demonstration

    try:
        url = f"https://api.tomtom.com/traffic/services/4/flowSegmentData/relative-delay/10/json?key={api_key}&point={lat},{lng}"
        res = requests.get(url, timeout=4).json()
        flow = res.get('flowSegmentData', {})
        current_speed = flow.get('currentSpeed', 50)
        free_flow_speed = flow.get('freeFlowSpeed', 50)
        return round(max(1.0, free_flow_speed / max(current_speed, 1)), 2)
    except Exception:
        return 2.2

def load_city_data(city_name):
    full_name = f"{city_name}, Illinois, USA"
    if full_name not in city_cache:
        G_raw = ox.graph_from_place(full_name, network_type='drive')
        G = G_raw.subgraph(max(nx.strongly_connected_components(G_raw), key=len)).copy()
        G = ox.add_edge_speeds(G)
        G = ox.add_edge_travel_times(G)
        city_cache[full_name] = G
    return city_cache[full_name]

def get_addr_fast(lat, lng):
    key = (round(lat, 4), round(lng, 4))
    if key not in address_cache:
        try:
            loc = geolocator.reverse((lat, lng), timeout=2)
            address_cache[key] = ", ".join(loc.address.split(',')[:3])
        except:
            address_cache[key] = f"GPS: {lat:.4f}, {lng:.4f}"
    return address_cache[key]

# --- 4. EXTENDED ML ENGINE ---
def train_ml_models():
    np.random.seed(42)
    n_samples = 3000
    data = {
        'hour': np.random.randint(0, 24, n_samples),
        'day_of_week': np.random.randint(0, 7, n_samples),
        'is_weekend': np.random.choice([0, 1], n_samples),
        'precipitation': np.random.uniform(0, 10, n_samples),
        'traffic_level': np.random.uniform(1.0, 3.0, n_samples),
        'roadworks_density': np.random.uniform(0.0, 1.0, n_samples),
        'temperature': np.random.uniform(-10, 35, n_samples),
        'event_factor': np.random.choice([0, 1], n_samples, p=[0.8, 0.2]),
        'lat': np.random.uniform(41.80, 41.85, n_samples),
        'lng': np.random.uniform(-87.83, -87.78, n_samples),
    }
    df = pd.DataFrame(data)

    raw_risk = (
        (df['hour'] >= 18) * 1.5 +
        (df['precipitation'] > 3) * 1.3 +
        (df['traffic_level'] > 1.5) * 1.2 +
        np.random.uniform(0.1, 0.4, n_samples)
    )
    df['incident_risk'] = np.random.poisson(lam=raw_risk)

    features = [
        'hour', 'day_of_week', 'is_weekend', 'precipitation',
        'traffic_level', 'roadworks_density', 'temperature', 'event_factor',
        'lat', 'lng'
    ]

    models = {
        'Poisson Regression (Rare Events)': PoissonRegressor(max_iter=300),
        'XGBoost Regressor': xgb.XGBRegressor(n_estimators=50, random_state=42, verbosity=0),
        'LightGBM Regressor': lgb.LGBMRegressor(n_estimators=50, random_state=42, verbose=-1),
        'Random Forest': RandomForestRegressor(n_estimators=50, random_state=42),
        'Gradient Boosting': GradientBoostingRegressor(n_estimators=50, random_state=42),
        'Linear Regression': LinearRegression()
    }

    for name, model in models.items():
        model.fit(df[features], df['incident_risk'])

    return models, features

trained_models, feature_names = train_ml_models()

# --- 5. DETOUR ROUTING ENGINE ---
def compute_route_with_detour(G, start_node, target_node, traffic_factor):
    """
    UA: Обчислює основний та об'їзний маршрути у разі критичних заторів (>2.0x).
    EN: Computes direct and detour routes when critical traffic (>2.0x) is detected.
    """
    # 1. Standard traffic-adjusted weights
    for u, v, k, data in G.edges(keys=True, data=True):
        base_t = data.get('travel_time', 10.0)
        data['live_weight'] = base_t * traffic_factor

    direct_path = nx.shortest_path(G, start_node, target_node, weight='live_weight')
    direct_eta = nx.shortest_path_length(G, start_node, target_node, weight='live_weight')

    # 2. Check if critical congestion triggers a detour requirement
    if traffic_factor > 2.0:
        # Penalize main congested corridor edges to force alternative route finding
        G_temp = G.copy()
        for i in range(len(direct_path) - 1):
            u, v = direct_path[i], direct_path[i+1]
            if G_temp.has_edge(u, v):
                for k in G_temp[u][v]:
                    G_temp[u][v][k]['detour_weight'] = G_temp[u][v][k]['live_weight'] * 4.0

        for u, v, k, data in G_temp.edges(keys=True, data=True):
            if 'detour_weight' not in data:
                data['detour_weight'] = data['live_weight']

        try:
            detour_path = nx.shortest_path(G_temp, start_node, target_node, weight='detour_weight')
            detour_eta = nx.shortest_path_length(G_temp, start_node, target_node, weight='live_weight')
            return direct_path, direct_eta, detour_path, detour_eta, True
        except nx.NetworkXNoPath:
            pass

    return direct_path, direct_eta, None, None, False

# --- 6. UI COMPONENTS ---
out_map1 = widgets.Output(layout={'width': '50%', 'height': '500px', 'border': '2px solid #2980b9'})
out_map2 = widgets.Output(layout={'width': '50%', 'height': '500px', 'border': '2px solid #c0392b'})
out_hist = widgets.Output(layout={'width': '100%', 'height': '240px'})

out_text = widgets.HTML(
    value="<div style='border:1px solid #ccc; padding:15px; background:#fdfdfd; font-family:monospace; border-radius:5px;'>"
          "<b>Guardian AI Ready. Critical Congestion Detour Routing Active (>2.0x).</b></div>",
    layout={'width': '100%'}
)

download_btn_holder = widgets.HTML(layout={'width': '100%', 'margin': '5px 0'})

algo_drop = widgets.Dropdown(
    options=[
        'Poisson Regression (Rare Events)',
        'XGBoost Regressor',
        'LightGBM Regressor',
        'Random Forest',
        'Gradient Boosting',
        'Linear Regression'
    ],
    value='Poisson Regression (Rare Events)',
    description='<b>ML Model:</b>'
)

city_drop = widgets.Dropdown(options=['Riverside', 'North Riverside', 'Brookfield'], value='Riverside', description='<b>City:</b>')
car_slider = widgets.IntSlider(value=10, min=4, max=15, step=1, description='<b>Patrols:</b>', continuous_update=False)

# Context Controls
hour_slider = widgets.IntSlider(value=20, min=0, max=23, step=1, description='<b>Hour:</b>', continuous_update=False)
rain_slider = widgets.FloatSlider(value=0.0, min=0.0, max=10.0, step=0.1, description='<b>Rain (mm):</b>', continuous_update=False)
traffic_slider = widgets.FloatSlider(value=2.2, min=1.0, max=3.0, step=0.1, description='<b>Traffic:</b>', continuous_update=False)
roadworks_slider = widgets.FloatSlider(value=0.2, min=0.0, max=1.0, step=0.1, description='<b>Roadworks:</b>', continuous_update=False)
temp_slider = widgets.IntSlider(value=20, min=-10, max=35, step=1, description='<b>Temp (°C):</b>', continuous_update=False)
event_check = widgets.Checkbox(value=False, description='<b>Mass Event Active</b>')

btn_fetch_api = widgets.Button(description="FETCH LIVE API DATA", button_style='warning', layout={'width': '23%', 'height': '40px'})
btn_opt = widgets.Button(description="1. OPTIMIZE DEPLOYMENT", button_style='primary', layout={'width': '25%', 'height': '40px'})
btn_sim = widgets.Button(description="2. SIMULATE & REPOSITION", button_style='danger', layout={'width': '25%', 'height': '40px'})
btn_export = widgets.Button(description="3. EXPORT REPORT", button_style='info', layout={'width': '22%', 'height': '40px'})

state = {'G': None, 'nodes': [], 'opt_positions': [], 'before_addresses': [], 'last_df': None, 'risk_df': None}

# --- 7. HELPER FUNCTIONS ---
def create_interactive_map(location, zoom=14):
    return folium.Map(
        location=location,
        zoom_start=zoom,
        tiles=TILE_PROVIDER,
        zoom_control=True,
        scrollWheelZoom=True
    )

def render_stable_map(out_widget, map_obj):
    with out_widget:
        clear_output(wait=True)
        display(HTML(f'<div style="width:100%; height:480px;">{map_obj._repr_html_()}</div>'))

def find_weighted_clusters(G, k, context, selected_algo):
    nodes_gdf = ox.graph_to_gdfs(G, edges=False)
    df_nodes = pd.DataFrame({
        'node_id': nodes_gdf.index,
        'lat': nodes_gdf.geometry.y,
        'lng': nodes_gdf.geometry.x,
        'hour': context['hour'],
        'day_of_week': 5,
        'is_weekend': 1,
        'precipitation': context['precipitation'],
        'traffic_level': context['traffic_level'],
        'roadworks_density': context['roadworks_density'],
        'temperature': context['temperature'],
        'event_factor': context['event_factor']
    })

    active_model = trained_models[selected_algo]
    predicted_risk = active_model.predict(df_nodes[feature_names])
    df_nodes['predicted_risk'] = np.clip(predicted_risk, a_min=0.01, a_max=None)

    coords = df_nodes[['lat', 'lng']].values
    weights = df_nodes['predicted_risk'].values

    kmeans = KMeans(n_clusters=k, random_state=42, n_init=5).fit(coords, sample_weight=weights)
    best_nodes = [ox.distance.nearest_nodes(G, lon, lat) for lat, lon in kmeans.cluster_centers_]

    return best_nodes, df_nodes

def create_download_link(df, filename="guardian_ai_detour_report.csv"):
    csv_str = df.to_csv(index=False)
    b64 = base64.b64encode(csv_str.encode()).decode()
    return f'<a download="{filename}" href="data:text/csv;base64,{b64}" target="_blank" style="display:inline-block; padding:8px 15px; background-color:#27ae60; color:white; text-decoration:none; border-radius:4px; font-weight:bold;">Download CSV Report</a>'

# --- 8. EVENT HANDLERS ---
def on_fetch_api_click(b):
    if state['G'] is None: return
    G = state['G']
    center_lat = G.nodes[state['nodes'][0]]['y']
    center_lng = G.nodes[state['nodes'][0]]['x']

    weather_data = fetch_live_weather(center_lat, center_lng)
    traffic_val = fetch_live_traffic_factor(center_lat, center_lng)

    temp_slider.value = int(weather_data['temp'])
    rain_slider.value = float(weather_data['rain'])
    traffic_slider.value = float(traffic_val)

    out_text.value = (
        f"<div style='background:#e8f8f5; padding:15px; border-left:5px solid #1abc9c; font-family:monospace;'>"
        f"<b>LIVE API DATA LOADED!</b><br>"
        f"<b>Temperature:</b> {weather_data['temp']}°C | "
        f"<b>Rainfall:</b> {weather_data['rain']} mm | "
        f"<b>Traffic Multiplier:</b> {traffic_val}x "
        f"({'CRITICAL CONGESTION DETOUR ACTIVE' if traffic_val > 2.0 else 'Normal Flow'})"
        f"</div>"
    )

def on_city_select(change):
    city = change['new']
    out_text.value = f"<div style='padding:15px; font-family:monospace;'>Loading road network for <b>{city}</b>...</div>"

    state['G'] = load_city_data(city)
    state['nodes'] = list(state['G'].nodes())
    state['opt_positions'] = []
    state['last_df'] = None
    download_btn_holder.value = ""

    G = state['G']
    center = [G.nodes[state['nodes'][0]]['y'], G.nodes[state['nodes'][0]]['x']]

    m1 = create_interactive_map(center, zoom=14)
    m2 = create_interactive_map(center, zoom=14)

    render_stable_map(out_map1, m1)
    render_stable_map(out_map2, m2)
    on_fetch_api_click(None)

def on_opt_click(b):
    if state['G'] is None: return
    btn_opt.disabled = True
    G = state['G']
    k = car_slider.value
    selected_algo = algo_drop.value

    context = {
        'hour': hour_slider.value,
        'precipitation': rain_slider.value,
        'traffic_level': traffic_slider.value,
        'roadworks_density': roadworks_slider.value,
        'temperature': temp_slider.value,
        'event_factor': 1 if event_check.value else 0
    }

    state['opt_positions'], state['risk_df'] = find_weighted_clusters(G, k, context, selected_algo)
    state['before_addresses'] = []

    center = [G.nodes[state['opt_positions'][0]]['y'], G.nodes[state['opt_positions'][0]]['x']]
    m1 = create_interactive_map(center, zoom=14)

    heat_data = state['risk_df'][['lat', 'lng', 'predicted_risk']].values.tolist()
    HeatMap(heat_data, radius=15, blur=10, max_zoom=1).add_to(m1)

    report_rows = []
    log = "<div style='background:#f4f6f7; padding:15px; border-radius:5px; border-left:5px solid #2980b9; font-family:monospace;'>"
    log += f"<h2>DEPLOYMENT OPTIMIZATION ({selected_algo.upper()})</h2>"
    log += f"<b>Live Traffic:</b> {context['traffic_level']}x | <b>Rain:</b> {context['precipitation']} mm<br><hr>"
    log += "<table border='1' cellpadding='6' cellspacing='0' style='width:100%; border-collapse:collapse; background:white;'>"
    log += "<tr style='background:#2980b9; color:white;'><th>Unit #</th><th>Node ID</th><th>Coordinates</th><th>Assigned Address</th></tr>"

    for i, n in enumerate(state['opt_positions']):
        lat, lng = G.nodes[n]['y'], G.nodes[n]['x']
        addr = get_addr_fast(lat, lng)
        state['before_addresses'].append(addr)

        folium.Circle([lat, lng], radius=350, color='blue', fill=True, fill_opacity=0.2).add_to(m1)
        folium.Marker([lat, lng], tooltip=f"[{selected_algo}] Unit #{i+1}: {addr}", icon=folium.Icon(color='blue', icon='car', prefix='fa')).add_to(m1)

        log += f"<tr><td>Unit #{i+1}</td><td>{n}</td><td>{lat:.5f}, {lng:.5f}</td><td>{addr}</td></tr>"
        report_rows.append({
            'Algorithm': selected_algo,
            'Unit_ID': f"Unit #{i+1}",
            'Node_ID': n,
            'Latitude': lat,
            'Longitude': lng,
            'Address': addr
        })

    log += "</table></div>"
    state['last_df'] = pd.DataFrame(report_rows)

    render_stable_map(out_map1, m1)
    out_text.value = log
    btn_opt.disabled = False

def on_sim_click(b):
    if not state['opt_positions']:
        out_text.value = "<div style='color:red; font-family:monospace; padding:15px;'><b>Please run '1. OPTIMIZE DEPLOYMENT' first!</b></div>"
        return

    btn_sim.disabled = True
    G = state['G']
    k_total = car_slider.value
    opt_pos_before = state['opt_positions']
    selected_algo = algo_drop.value

    risk_df = state['risk_df']
    probabilities = risk_df['predicted_risk'] / risk_df['predicted_risk'].sum()
    selected_row = risk_df.sample(1, weights=probabilities).iloc[0]
    incident = int(selected_row['node_id'])

    inc_lat, inc_lng = G.nodes[incident]['y'], G.nodes[incident]['x']
    inc_addr = get_addr_fast(inc_lat, inc_lng)
    traffic_factor = traffic_slider.value

    dists = []
    for i, car in enumerate(opt_pos_before):
        try:
            d_path, d_eta, detour_path, detour_eta, has_detour = compute_route_with_detour(G, car, incident, traffic_factor)
            dists.append((i, d_eta, d_path, detour_path, detour_eta, has_detour))
        except Exception:
            continue

    dists.sort(key=lambda x: x[1])
    dispatch_count = min(2, len(dists))
    resp_units = dists[:dispatch_count]

    context = {
        'hour': hour_slider.value,
        'precipitation': rain_slider.value,
        'traffic_level': traffic_slider.value,
        'roadworks_density': roadworks_slider.value,
        'temperature': temp_slider.value,
        'event_factor': 1 if event_check.value else 0
    }
    remaining_cars_count = k_total - dispatch_count
    opt_pos_after, _ = find_weighted_clusters(G, remaining_cars_count, context, selected_algo)

    m2 = create_interactive_map([inc_lat, inc_lng], zoom=14)
    heat_data = risk_df[['lat', 'lng', 'predicted_risk']].values.tolist()
    HeatMap(heat_data, radius=15, blur=10, max_zoom=1).add_to(m2)

    folium.Marker([inc_lat, inc_lng], icon=folium.Icon(color='red', icon='warning', prefix='fa'), tooltip=f"CALL 911: {inc_addr}").add_to(m2)

    log = "<div style='background:#fdfefe; padding:15px; border-radius:5px; border-left:5px solid #c0392b; font-family:monospace;'>"
    log += f"<h2 style='color:#c0392b;'>CALL 911 DISPATCH & DETOUR ROUTING ({selected_algo.upper()})</h2>"
    log += f"<b>INCIDENT LOCATION:</b> {inc_addr} | <b>Traffic Multiplier:</b> {traffic_factor}x<br><hr>"

    if traffic_factor > 2.0:
        log += "<div style='background:#f9ebea; color:#c0392b; padding:10px; border-radius:4px; margin-bottom:10px;'><b>CRITICAL CONGESTION ALERT (>2.0x): DETOUR ROUTING ACTIVATED!</b></div>"

    log += "<h3>1. Emergency Response Units Dispatched</h3>"
    log += "<table border='1' cellpadding='6' cellspacing='0' style='width:100%; border-collapse:collapse; background:white; margin-bottom:15px;'>"
    log += "<tr style='background:#c0392b; color:white;'><th>Rank</th><th>Unit #</th><th>Dispatched Address</th><th>Direct ETA</th><th>Detour Routing ETA</th></tr>"

    for order, (idx, d_eta, d_path, detour_path, detour_eta, has_detour) in enumerate(resp_units):
        n = opt_pos_before[idx]
        unit_lat, unit_lng = G.nodes[n]['y'], G.nodes[n]['x']

        # Draw Direct Congested Route (Red Line)
        direct_coords = [[G.nodes[node]['y'], G.nodes[node]['x']] for node in d_path]
        folium.PolyLine(locations=direct_coords, color='red', weight=4, opacity=0.6, tooltip=f"Direct Route Unit #{idx+1} ({int(d_eta)}s)").add_to(m2)

        # Draw Detour Bypass Route (Green Dashed Line) if critical congestion detected
        if has_detour and detour_path:
            detour_coords = [[G.nodes[node]['y'], G.nodes[node]['x']] for node in detour_path]
            folium.PolyLine(locations=detour_coords, color='green', weight=5, opacity=0.9, dash_array='8, 8', tooltip=f"DETOUR BYPASS Unit #{idx+1} ({int(detour_eta)}s)").add_to(m2)
            detour_str = f"<b style='color:green;'>{int(detour_eta)} sec (Detour)</b>"
        else:
            detour_str = "N/A"

        folium.Marker([unit_lat, unit_lng], icon=folium.Icon(color='red', icon='bolt', prefix='fa'), tooltip=f"Unit #{idx+1} Dispatched").add_to(m2)
        log += f"<tr><td>Priority #{order+1}</td><td>Unit #{idx+1}</td><td>{state['before_addresses'][idx]}</td><td>{int(d_eta)} sec</td><td>{detour_str}</td></tr>"

    log += "</table>"

    log += f"<h3>2. Dynamic Patrol Repositioning ({remaining_cars_count} Units)</h3>"
    log += "<table border='1' cellpadding='6' cellspacing='0' style='width:100%; border-collapse:collapse; background:white;'>"
    log += "<tr style='background:#27ae60; color:white;'><th>Position #</th><th>Node ID</th><th>New Standby Address</th></tr>"

    for i, n in enumerate(opt_pos_after):
        lat, lng = G.nodes[n]['y'], G.nodes[n]['x']
        addr_after = get_addr_fast(lat, lng)
        folium.Circle([lat, lng], radius=400, color='green', fill=True, fill_opacity=0.25).add_to(m2)
        folium.Marker([lat, lng], icon=folium.Icon(color='green', icon='shield', prefix='fa'), tooltip=f"[REPOSITIONED] Standby #{i+1}: {addr_after}").add_to(m2)

        log += f"<tr><td>Green Zone #{i+1}</td><td>{n}</td><td>{addr_after}</td></tr>"

    log += "</table></div>"

    with out_hist:
        clear_output(wait=True)
        plt.figure(figsize=(10, 2.5))
        plt.hist(np.random.normal(210 * traffic_factor, 30), bins=15, color='#27ae60', alpha=0.75, edgecolor='black')
        plt.title(f"Response Time Distribution with Detour Active (Traffic: {traffic_factor:.1f}x)")
        plt.xlabel("Response Time (Seconds)")
        plt.ylabel("Frequency")
        plt.grid(True, linestyle='--', alpha=0.5)
        plt.tight_layout()
        plt.show()

    render_stable_map(out_map2, m2)
    out_text.value = log
    btn_sim.disabled = False

def on_export_click(b):
    if state['last_df'] is not None:
        download_btn_holder.value = create_download_link(state['last_df'])

# --- 9. BINDINGS & LAYOUT ---
city_drop.observe(on_city_select, names='value')
btn_fetch_api.on_click(on_fetch_api_click)
btn_opt.on_click(on_opt_click)
btn_sim.on_click(on_sim_click)
btn_export.on_click(on_export_click)

display(widgets.VBox([
    widgets.HTML("<div style='background:#2c3e50; color:white; padding:15px; text-align:center; border-radius:5px;'><h1>Guardian AI (Detour Routing & Multi-API Integration)</h1></div>"),
    widgets.HBox([out_map1, out_map2]),
    widgets.VBox([
        widgets.HBox([city_drop, algo_drop, car_slider, hour_slider], layout={'justify_content': 'center', 'padding': '5px'}),
        widgets.HBox([rain_slider, traffic_slider, roadworks_slider, temp_slider, event_check], layout={'justify_content': 'center', 'padding': '5px'}),
        widgets.HBox([btn_fetch_api, btn_opt, btn_sim, btn_export], layout={'justify_content': 'space-around', 'padding': '10px'}),
        download_btn_holder
    ], layout={'border': '1px solid #ddd', 'background': '#f9f9f9', 'margin': '10px 0', 'padding': '10px'}),
    out_hist,
    out_text
]))

# Initial startup
on_city_select({'new': 'Riverside'})